### ISSUE TITLE
ArticleList View Thumbnails

### ISSUE THREAD

**Issue by gautampadiyar** [gautampadiyar/Khmd_Reader#7]
As the list view is scrolled, during recreation of the individual views, the thumbnails are getting displaced from their original positions. 
This is happening only on slower networks due to recurring need to download images. 

![2015-02-16 1](https://cloud.githubusercontent.com/assets/5158168/6215628/61b0c7ca-b628-11e4-9dd6-675ed08c5338.jpg)

**Comment by arjun-rao** [comment]
Again, this will probably be solved when we cache the images, are you currently testing on device or simulator?

**Comment by gautampadiyar** [comment]
Tested on multiple devices. The fastest I got is 4 secs. Again check my other answer :)
